# Generated by Django 6.0.2 on 2026-03-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0002_announcement_banner_event_news_program_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
