# Generated by Django 6.0.2 on 2026-03-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0003_delete_banner_delete_news_delete_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
    ]
