# Generated by Django 6.0.2 on 2026-03-10 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0005_departmentchair_officedean_delete_officemember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officedean',
            name='department',
        ),
    ]
