# Generated by Django 6.0.2 on 2026-03-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0006_remove_officedean_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('deans', 'Office of the Dean'), ('chair', 'Department Chairpersons')], max_length=10)),
                ('position', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DepartmentChair',
        ),
        migrations.DeleteModel(
            name='OfficeDean',
        ),
    ]
