# Generated by Django 6.0.2 on 2026-03-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0007_officemember_delete_departmentchair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officemember',
            name='category',
            field=models.CharField(choices=[('dean', 'Office of the Dean'), ('chair', 'Department Chairpersons')], max_length=10),
        ),
    ]
