# Generated by Django 6.0.2 on 2026-03-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0008_alter_officemember_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officemember',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='officemember',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
