# Generated by Django 6.0.2 on 2026-03-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0009_alter_officemember_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficeMember',
        ),
    ]
