# Generated by Django 6.0.2 on 2026-03-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0010_delete_officemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('dean', 'Office of the Dean'), ('chair', 'Department Chairpersons')], max_length=10)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
