# Generated by Django 6.0.2 on 2026-03-10 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0011_officemember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficeMember',
        ),
    ]
