# Generated by Django 6.0.2 on 2026-03-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0012_delete_officemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('dean', 'Office of the Dean'), ('chair', 'Department Chairpersons')], max_length=10)),
                ('position', models.CharField(choices=[('Dean', 'Dean'), ('AsstDean', 'Assistant Dean'), ('chair', 'Chairperson')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('rank', models.CharField(choices=[('PhD', 'Doctor of Philosophy'), ('DiSDS', 'Doctor in Sustainable Development Studies'), ('MSc', 'Master of Science')], max_length=10)),
                ('department', models.CharField(choices=[('envisci', 'Department of Environmental Science'), ('sds', 'Sustainable Development Studies'), ('datasci', 'Data Science Program')], max_length=10)),
            ],
        ),
    ]
