# Generated by Django 6.0.2 on 2026-03-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0013_officemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officemember',
            name='department',
            field=models.CharField(blank=True, choices=[('envisci', 'Department of Environmental Science'), ('sds', 'Sustainable Development Studies'), ('datasci', 'Data Science Program')], max_length=10, null=True),
        ),
    ]
