# Generated by Django 6.0.2 on 2026-03-10 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0014_alter_officemember_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficeMember',
        ),
    ]
