# Generated by Django 6.0.2 on 2026-03-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0015_delete_officemember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='Home_Announcement',
        ),
        migrations.RenameModel(
            old_name='Event',
            new_name='Home_Event',
        ),
    ]
