# Generated by Django 6.0.2 on 2026-03-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0016_rename_announcement_home_announcement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDeans_DeptChair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Department of Environmental Science', 'Envi'), ('Sustainable Development Studies', 'Sds'), ('Data Science Program', 'Ds')], max_length=40)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AboutDeans_OfficeDeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('dean', 'Dean'), ('assistant_dean', 'Assistant Dean')], max_length=20)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
