# Generated by Django 6.0.2 on 2026-03-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0017_aboutdeans_deptchair_aboutdeans_officedeans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdeans_officedeans',
            name='position',
            field=models.CharField(choices=[('dean', 'Dean'), ('assistant_dean', 'Assistant Dean')], max_length=20, unique=True),
        ),
    ]
