# Generated by Django 6.0.2 on 2026-03-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0018_alter_aboutdeans_officedeans_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdeans_deptchair',
            name='department',
            field=models.CharField(choices=[('Department of Environmental Science', 'Envi'), ('Sustainable Development Studies', 'Sds'), ('Data Science Program', 'Ds')], max_length=40, unique=True),
        ),
    ]
