# Generated by Django 6.0.2 on 2026-03-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0019_alter_aboutdeans_deptchair_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdeans_deptchair',
            name='department',
            field=models.CharField(choices=[('Envi', 'Department of Environmental Science'), ('Sds', 'Sustainable Development Studies'), ('Ds', 'Data Science Program')], max_length=40, unique=True),
        ),
    ]
