# Generated by Django 6.0.2 on 2026-03-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0020_alter_aboutdeans_deptchair_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdeans_deptchair',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='aboutdeans_officedeans',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
