# Generated by Django 6.0.2 on 2026-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0021_aboutdeans_deptchair_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdeans_deptchair',
            name='title',
            field=models.CharField(blank=True, choices=[('phd', 'PhD'), ('disds', 'DiSDS'), ('msc', 'MSc')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aboutdeans_officedeans',
            name='title',
            field=models.CharField(blank=True, choices=[('phd', 'PhD'), ('disds', 'DiSDS'), ('msc', 'MSc')], max_length=10, null=True),
        ),
    ]
