# Generated by Django 6.0.2 on 2026-03-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0022_alter_aboutdeans_deptchair_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPM_Curr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('First', '1'), ('Summer', 'S'), ('Second', '2')], max_length=10)),
                ('sem', models.CharField(choices=[('First', '1'), ('Second', '2')], max_length=10)),
                ('major', models.CharField(max_length=60)),
            ],
        ),
    ]
