# Generated by Django 6.0.2 on 2026-03-24 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0023_epm_curr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EPM_Curr',
        ),
    ]
