# Generated by Django 6.0.2 on 2026-03-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0024_delete_epm_curr'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPM_Curr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('First', '1'), ('Summer', 'S'), ('Second', '2'), ('Major', 'M')], max_length=10)),
                ('sem', models.CharField(choices=[('First', '1'), ('Second', '2')], max_length=10)),
                ('subjects', models.CharField(max_length=200)),
            ],
        ),
    ]
