# Generated by Django 6.0.2 on 2026-03-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0028_alter_subjects_curr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
