# Generated by Django 6.0.2 on 2026-03-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0029_delete_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr', models.CharField(choices=[('Environmental Planning and Management', 'epm'), ('Environmental Research', 'er'), ('PhD in Environmental Science', 'esphd'), ('MSDS - Community Development', 'msds_comdev'), ('MSDS - Economic Development', 'msds_econdev'), ('MSDS - Environmental Education', 'msds_envied'), ('MSDS - Environmental Engineering', 'msds_enviengg'), ('MSDS - Resource Management', 'msds_resmgt'), ('MSDS - Rural and Urban Planning', 'msds_rup'), ('MSDS - Peace and Conflict Transformation', 'msds_pct'), ('DSDS without - Community Development', 'dsds_without_comdev'), ('DSDS without - Economic Development', 'dsds_without_econdev'), ('DSDS without - Environmental Education', 'dsds_without_envied'), ('DSDS without - Environmental Engineering', 'dsds_without_enviengg'), ('DSDS without - Resource Management', 'dsds_without_resmgt'), ('DSDS without - Rural and Urban Planning', 'dsds_without_rup'), ('DSDS without - Peace and Conflict Transformation', 'dsds_without_pct'), ('DSDS with - Community Development', 'dsds_with_comdev'), ('DSDS with - Economic Development', 'dsds_with_econdev'), ('DSDS with - Environmental Education', 'dsds_with_envied'), ('DSDS with - Environmental Engineering', 'dsds_with_enviengg'), ('DSDS with - Resource Management', 'dsds_with_resmgt'), ('DSDS with - Rural and Urban Planning', 'dsds_with_rup'), ('DSDS with - Peace and Conflict Transformation', 'dsds_with_pct'), ('PhD SDS without - Community Development', 'phdsds_without_comdev'), ('PhD SDS without - Economic Development', 'phdsds_without_econdev'), ('PhD SDS without - Environmental Education', 'phdsds_without_envied'), ('PhD SDS without - Environmental Engineering', 'phdsds_without_enviengg'), ('PhD SDS without - Resource Management', 'phdsds_without_resmgt'), ('PhD SDS without - Rural and Urban Planning', 'phdsds_without_rup'), ('PhD SDS without - Peace and Conflict Transformation', 'phdsds_without_pct'), ('PhD SDS with - Community Development', 'phdsds_with_comdev'), ('PhD SDS with - Economic Development', 'phdsds_with_econdev'), ('PhD SDS with - Environmental Education', 'phdsds_with_envied'), ('PhD SDS with - Environmental Engineering', 'phdsds_with_enviengg'), ('PhD SDS with - Resource Management', 'phdsds_with_resmgt'), ('PhD SDS with - Rural and Urban Planning', 'phdsds_with_rup'), ('PhD SDS with - Peace and Conflict Transformation', 'phdsds_with_pct'), ('Master in Data Science', 'mds')], max_length=62)),
                ('year', models.CharField(choices=[('First', '1'), ('Summer', 'S'), ('Second', '2'), ('Major', 'M')], max_length=10)),
                ('sem', models.CharField(choices=[('First', '1'), ('Second', '2')], max_length=10)),
                ('subjects', models.JSONField(default=list)),
            ],
        ),
    ]
