# Generated by Django 6.0.2 on 2026-03-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0030_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
