# Generated by Django 6.0.2 on 2026-03-25 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0032_epm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EPM',
        ),
    ]
