# Generated by Django 6.0.2 on 2026-03-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0035_er'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('FYFS', 'First Year | First Sem'), ('FYSS', 'First Year | Second Sem'), ('FYS', 'First Year | Summer'), ('SYFS', 'Second Year | First Sem'), ('SYSS', 'Second Year | Second Sem'), ('M', 'Major')], max_length=32)),
                ('subject', models.CharField(max_length=51)),
            ],
        ),
    ]
