# Generated by Django 6.0.2 on 2026-04-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0037_sds_msds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sds_msds',
            name='subject',
            field=models.CharField(max_length=101),
        ),
    ]
