# Generated by Django 6.0.2 on 2026-04-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0039_sds_mssds'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDS_DSDSw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog', models.CharField(choices=[('COMDEV', 'Community Development'), ('ECONDEV', 'Economic Development'), ('ENVIED', 'Environmental Education'), ('ENVIENGG', 'Environmental Engineering'), ('RESMGT', 'Resource Management'), ('RUP', 'Rural and Urban Planning'), ('PCT', 'Peace and Conflict Transformation')], max_length=32)),
                ('year', models.CharField(choices=[('FYFS', 'First Year | First Sem'), ('FYSS', 'First Year | Second Sem'), ('FYS', 'First Year | Summer'), ('SYFS', 'Second Year | First Sem'), ('SYSS', 'Second Year | Second Sem'), ('M', 'Major')], max_length=32)),
                ('subject', models.CharField(max_length=101)),
            ],
        ),
        migrations.CreateModel(
            name='SDS_DSDSwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog', models.CharField(choices=[('COMDEV', 'Community Development'), ('ECONDEV', 'Economic Development'), ('ENVIED', 'Environmental Education'), ('ENVIENGG', 'Environmental Engineering'), ('RESMGT', 'Resource Management'), ('RUP', 'Rural and Urban Planning'), ('PCT', 'Peace and Conflict Transformation')], max_length=32)),
                ('year', models.CharField(choices=[('FYFS', 'First Year | First Sem'), ('FYSS', 'First Year | Second Sem'), ('FYS', 'First Year | Summer'), ('SYFS', 'Second Year | First Sem'), ('SYSS', 'Second Year | Second Sem'), ('M', 'Major')], max_length=32)),
                ('subject', models.CharField(max_length=101)),
            ],
        ),
        migrations.CreateModel(
            name='SDS_PhDSDSw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog', models.CharField(choices=[('COMDEV', 'Community Development'), ('ECONDEV', 'Economic Development'), ('ENVIED', 'Environmental Education'), ('ENVIENGG', 'Environmental Engineering'), ('RESMGT', 'Resource Management'), ('RUP', 'Rural and Urban Planning'), ('PCT', 'Peace and Conflict Transformation')], max_length=32)),
                ('year', models.CharField(choices=[('FYFS', 'First Year | First Sem'), ('FYSS', 'First Year | Second Sem'), ('FYS', 'First Year | Summer'), ('SYFS', 'Second Year | First Sem'), ('SYSS', 'Second Year | Second Sem'), ('M', 'Major')], max_length=32)),
                ('subject', models.CharField(max_length=101)),
            ],
        ),
        migrations.CreateModel(
            name='SDS_PhDSDSwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog', models.CharField(choices=[('COMDEV', 'Community Development'), ('ECONDEV', 'Economic Development'), ('ENVIED', 'Environmental Education'), ('ENVIENGG', 'Environmental Engineering'), ('RESMGT', 'Resource Management'), ('RUP', 'Rural and Urban Planning'), ('PCT', 'Peace and Conflict Transformation')], max_length=32)),
                ('year', models.CharField(choices=[('FYFS', 'First Year | First Sem'), ('FYSS', 'First Year | Second Sem'), ('FYS', 'First Year | Summer'), ('SYFS', 'Second Year | First Sem'), ('SYSS', 'Second Year | Second Sem'), ('M', 'Major')], max_length=32)),
                ('subject', models.CharField(max_length=101)),
            ],
        ),
    ]
