# Generated by Django 6.0.2 on 2026-04-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0040_sds_dsdsw_sds_dsdswo_sds_phdsdsw_sds_phdsdswo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('FYFS', 'First Year | First Sem'), ('FYSS', 'First Year | Second Sem'), ('FYS', 'First Year | Summer'), ('SYFS', 'Second Year | First Sem'), ('SYSS', 'Second Year | Second Sem'), ('M', 'Major')], max_length=32)),
                ('subject', models.CharField(max_length=51)),
            ],
        ),
    ]
