# Generated by Django 6.0.2 on 2026-04-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0041_mds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='faculties/')),
                ('names', models.CharField(max_length=62)),
            ],
        ),
    ]
