# Generated by Django 6.0.2 on 2026-04-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0043_delete_faculties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=62)),
                ('portrait', models.ImageField(upload_to='faculties/')),
                ('category', models.CharField(choices=[('FACULTY', 'facutly'), ('AFFILIATE', 'affiliate'), ('STAFF', 'staff')], default='FACULTY', max_length=12)),
            ],
        ),
    ]
