# Generated by Django 6.0.2 on 2026-04-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0044_faculties'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculties',
        ),
    ]
