# Generated by Django 6.0.2 on 2026-04-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0045_delete_faculties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=62)),
                ('potraits', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('FACULTY', 'faculty'), ('AFFILIATES', 'affiliates'), ('STAFF', 'staff'), ('OTHERS', 'others')], default='FACULTY', max_length=16)),
            ],
        ),
    ]
