# Generated by Django 6.0.2 on 2026-04-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0046_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='potraits',
            new_name='portraits',
        ),
    ]
