# Generated by Django 6.0.2 on 2026-04-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0047_rename_potraits_images_portraits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(max_length=62, unique=True),
        ),
    ]
