# Generated by Django 6.0.2 on 2026-04-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0048_alter_images_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
                ('category', models.CharField(choices=[('FACULTY', 'Faculty'), ('AFFILIATE', 'Affiliate'), ('STAFF', 'Staff')], max_length=12)),
                ('department', models.CharField(choices=[('ENVISCI', 'Environmental Science'), ('SUSTAINDEV', 'Sustainable Development'), ('DATASCI', 'Data Science')], max_length=12)),
                ('position', models.CharField(choices=[('DEAN', 'Dean'), ('ASSTDEAN', 'Assistant Dean'), ('CHAIRPERSON', 'Chairperson'), ('PRGCOORD', 'Program Coordinator')], max_length=12, unique=True)),
                ('rank', models.CharField(blank=True, choices=[('PROF', 'Professor'), ('ASSOC_DEAN', 'Associate Professor'), ('ASST_PROF', 'Assistant Prof'), ('LEC', 'Lecturer')], max_length=12, null=True)),
                ('title', models.CharField(blank=True, choices=[('DISDS', 'DiSDS'), ('MSC', 'MSc')], max_length=12, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
