# Generated by Django 6.0.2 on 2026-04-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0049_faculties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='title',
            field=models.CharField(blank=True, choices=[('PHD', 'PhD'), ('DISDS', 'DiSDS'), ('MSC', 'MSc')], max_length=12, null=True),
        ),
    ]
