# Generated by Django 6.0.2 on 2026-04-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0050_alter_faculties_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='position',
            field=models.CharField(choices=[('DEAN', 'Dean'), ('ASSTDEAN', 'Assistant Dean'), ('CHAIRPERSON', 'Chairperson'), ('PRGCOORD', 'Program Coordinator')], max_length=12),
        ),
    ]
