# Generated by Django 6.0.2 on 2026-04-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0051_alter_faculties_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='position',
            field=models.CharField(blank=True, choices=[('DEAN', 'Dean'), ('ASSTDEAN', 'Assistant Dean'), ('CHAIRPERSON', 'Chairperson'), ('PRGCOORD', 'Program Coordinator')], max_length=12, null=True),
        ),
    ]
