# Generated by Django 6.0.2 on 2026-04-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0052_alter_faculties_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='rank',
            field=models.CharField(blank=True, choices=[('PROF', 'Professor'), ('ASSOC_DEAN', 'Associate Professor'), ('ASSOC_LEC', 'Associate Lecturer'), ('ASST_PROF', 'Assistant Prof'), ('LEC', 'Lecturer')], max_length=12, null=True),
        ),
    ]
