# Generated by Django 6.0.2 on 2026-05-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0054_agendas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Downloadable Guides', 'Guides'), ('Admission Related', 'Admission'), ('Proposal Forms', 'Proposal'), ('Defense Forms', 'Defense'), ('Comprehensive Exam', 'Compre'), ('Registrar Forms', 'Registrar'), ('Research Ethics', 'RICO'), ('Quality Assurance', 'Quality'), ('Linkages', 'Links')], max_length=32)),
                ('resource', models.CharField(max_length=600)),
                ('links', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
