# Generated by Django 6.0.2 on 2026-05-12 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0055_resources'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutDeans_DeptChair',
        ),
        migrations.DeleteModel(
            name='AboutDeans_OfficeDeans',
        ),
        migrations.DeleteModel(
            name='Agendas',
        ),
        migrations.DeleteModel(
            name='EPM',
        ),
        migrations.DeleteModel(
            name='ER',
        ),
        migrations.DeleteModel(
            name='Faculties',
        ),
        migrations.DeleteModel(
            name='Home_Announcement',
        ),
        migrations.DeleteModel(
            name='Home_Event',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='MDS',
        ),
        migrations.DeleteModel(
            name='PhDER',
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
        migrations.DeleteModel(
            name='SDS_DSDSw',
        ),
        migrations.DeleteModel(
            name='SDS_DSDSwo',
        ),
        migrations.DeleteModel(
            name='SDS_MSDS',
        ),
        migrations.DeleteModel(
            name='SDS_MSSDS',
        ),
        migrations.DeleteModel(
            name='SDS_PhDSDSw',
        ),
        migrations.DeleteModel(
            name='SDS_PhDSDSwo',
        ),
    ]
