# Generated by Django 6.0.2 on 2026-05-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SISite', '0056_delete_aboutdeans_deptchair_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDeans_DeptChair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Envi', 'Department of Environmental Science'), ('Sds', 'Sustainable Development Studies'), ('Ds', 'Data Science Program')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, choices=[('phd', 'PhD'), ('disds', 'DiSDS'), ('msc', 'MSc')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutDeans_OfficeDeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('dean', 'Dean'), ('assistant_dean', 'Assistant Dean')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, choices=[('phd', 'PhD'), ('disds', 'DiSDS'), ('msc', 'MSc')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='EnviSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('EPM', 'MSES Environmental Planning and Management'), ('ER', 'MSES Environmental Research'), ('PHDES', 'PhD Environmental Science')], max_length=10)),
                ('year', models.CharField(choices=[('FYFS', 'First Year | First Sem'), ('FYSS', 'First Year | Second Sem'), ('FYS', 'First Year | Summer'), ('SYFS', 'Second Year | First Sem'), ('SYSS', 'Second Year | Second Sem'), ('M', 'Major')], max_length=32)),
                ('subject', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Environmental Science Subject',
                'verbose_name_plural': 'Environmental Science Subjects',
            },
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
                ('category', models.CharField(choices=[('FACULTY', 'Faculty'), ('AFFILIATE', 'Affiliate'), ('STAFF', 'Staff')], max_length=12)),
                ('department', models.CharField(choices=[('ENVISCI', 'Environmental Science'), ('SUSTAINDEV', 'Sustainable Development'), ('DATASCI', 'Data Science')], max_length=12)),
                ('position', models.CharField(blank=True, choices=[('DEAN', 'Dean'), ('ASSTDEAN', 'Assistant Dean'), ('CHAIRPERSON', 'Chairperson'), ('PRGCOORD', 'Program Coordinator')], max_length=12, null=True)),
                ('rank', models.CharField(blank=True, choices=[('PROF', 'Professor'), ('ASSOC_PROF', 'Associate Professor'), ('ASSOC_LEC', 'Associate Lecturer'), ('ASST_PROF', 'Assistant Professor'), ('LEC', 'Lecturer')], max_length=12, null=True)),
                ('title', models.CharField(blank=True, choices=[('phd', 'PhD'), ('disds', 'DiSDS'), ('msc', 'MSc')], max_length=12, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Home_Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Home_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('FYFS', 'First Year | First Sem'), ('FYSS', 'First Year | Second Sem'), ('FYS', 'First Year | Summer'), ('SYFS', 'Second Year | First Sem'), ('SYSS', 'Second Year | Second Sem'), ('M', 'Major')], max_length=32)),
                ('subject', models.CharField(max_length=51)),
            ],
            options={
                'verbose_name': 'MDS Subject',
                'verbose_name_plural': 'MDS Subjects',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Downloadable Guides', 'Downloadable Guides'), ('Admission Related', 'Admission Related'), ('Proposal Forms', 'Proposal Forms'), ('Defense Forms', 'Defense Forms'), ('Comprehensive Exam', 'Comprehensive Exam'), ('Registrar Forms', 'Registrar Forms'), ('Research Ethics', 'Research Ethics'), ('Quality Assurance', 'Quality Assurance'), ('Linkages', 'Linkages')], max_length=32)),
                ('resource', models.CharField(max_length=600)),
                ('links', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SDSSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('MSDS', 'Master of Science in Sustainable Development Studies'), ('MSSDS', 'Master in Sustainable Development Studies'), ('DSDSW', 'Doctor in SDS (with bridging)'), ('DSDSWO', 'Doctor in SDS (without bridging)'), ('PHDSDSW', 'PhD SDS (with bridging)'), ('PHDSDSWO', 'PhD SDS (without bridging)')], max_length=10)),
                ('prog', models.CharField(choices=[('COMDEV', 'Community Development'), ('ECONDEV', 'Economic Development'), ('ENVIED', 'Environmental Education'), ('ENVIENGG', 'Environmental Engineering'), ('RESMGT', 'Resource Management'), ('RUP', 'Rural and Urban Planning'), ('PCT', 'Peace and Conflict Transformation')], max_length=32)),
                ('year', models.CharField(choices=[('FYFS', 'First Year | First Sem'), ('FYSS', 'First Year | Second Sem'), ('FYS', 'First Year | Summer'), ('SYFS', 'Second Year | First Sem'), ('SYSS', 'Second Year | Second Sem'), ('M', 'Major')], max_length=32)),
                ('subject', models.CharField(max_length=101)),
            ],
            options={
                'verbose_name': 'SDS Subject',
                'verbose_name_plural': 'SDS Subjects',
            },
        ),
    ]
