# Generated by Django 6.0.2 on 2026-05-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0057_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutDeans_DeptChair',
        ),
        migrations.DeleteModel(
            name='AboutDeans_OfficeDeans',
        ),
    ]
