# Generated by Django 6.0.2 on 2026-05-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0058_delete_aboutdeans_deptchair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='title',
            field=models.CharField(blank=True, choices=[('PhD', 'PhD'), ('DiSDS', 'DiSDS'), ('MSc', 'MSc')], max_length=12, null=True),
        ),
    ]
