# Generated by Django 6.0.2 on 2026-05-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0059_alter_faculties_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='title',
            field=models.CharField(blank=True, choices=[('phd', 'PhD'), ('disds', 'DiSDS'), ('msc', 'MSc')], max_length=12, null=True),
        ),
    ]
