# Generated by Django 6.0.2 on 2026-05-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0062_alter_faculties_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='rank',
            field=models.CharField(blank=True, choices=[('Prof', 'Prof'), ('Assoc.Prof', 'Assoc.Prof'), ('Assoc.Lec', 'Assoc.Lec'), ('Asst.Prof', 'Asst.Prof'), ('Lec', 'Lec')], max_length=12, null=True),
        ),
    ]
