# Generated by Django 6.0.2 on 2026-05-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0064_alter_faculties_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envisubject',
            name='year',
            field=models.CharField(choices=[('FYFS', 'First Year | First Sem'), ('FYSS', 'First Year | Second Sem'), ('FYS', 'First Year | Summer'), ('SYFS', 'Second Year | First Sem'), ('SYSS', 'Second Year | Second Sem'), ('SYS', 'Second Year | Summer'), ('M', 'Major')], max_length=32),
        ),
        migrations.AlterField(
            model_name='mds',
            name='year',
            field=models.CharField(choices=[('FYFS', 'First Year | First Sem'), ('FYSS', 'First Year | Second Sem'), ('FYS', 'First Year | Summer'), ('SYFS', 'Second Year | First Sem'), ('SYSS', 'Second Year | Second Sem'), ('SYS', 'Second Year | Summer'), ('M', 'Major')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sdssubject',
            name='program_type',
            field=models.CharField(choices=[('MSDS', 'Master in Sustainable Development Studies'), ('MSSDS', 'Master of Science in Sustainable Development Studies'), ('DSDSW', 'Doctor in SDS (with bridging)'), ('DSDSWO', 'Doctor in SDS (without bridging)'), ('PHDSDSW', 'PhD SDS (with bridging)'), ('PHDSDSWO', 'PhD SDS (without bridging)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sdssubject',
            name='year',
            field=models.CharField(choices=[('FYFS', 'First Year | First Sem'), ('FYSS', 'First Year | Second Sem'), ('FYS', 'First Year | Summer'), ('SYFS', 'Second Year | First Sem'), ('SYSS', 'Second Year | Second Sem'), ('SYS', 'Second Year | Summer'), ('M', 'Major')], max_length=32),
        ),
    ]
