# Generated by Django 6.0.2 on 2026-06-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISite', '0065_alter_envisubject_year_alter_mds_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envisubject',
            name='POS_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculties',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mds',
            name='POS_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sdssubject',
            name='POS_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='envisubject',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='envisubject',
            name='year',
            field=models.CharField(choices=[('FYFS', 'First Year | First Sem'), ('FYSS', 'First Year | Second Sem'), ('FYS', 'First Year | Summer'), ('SYFS', 'Second Year | First Sem'), ('SYSS', 'Second Year | Second Sem'), ('SYS', 'Second Year | Summer'), ('M', 'Major'), ('POS', 'Program of Study')], max_length=32),
        ),
        migrations.AlterField(
            model_name='mds',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mds',
            name='year',
            field=models.CharField(choices=[('FYFS', 'First Year | First Sem'), ('FYSS', 'First Year | Second Sem'), ('FYS', 'First Year | Summer'), ('SYFS', 'Second Year | First Sem'), ('SYSS', 'Second Year | Second Sem'), ('SYS', 'Second Year | Summer'), ('M', 'Major'), ('POS', 'Program of Study')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sdssubject',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sdssubject',
            name='year',
            field=models.CharField(choices=[('FYFS', 'First Year | First Sem'), ('FYSS', 'First Year | Second Sem'), ('FYS', 'First Year | Summer'), ('SYFS', 'Second Year | First Sem'), ('SYSS', 'Second Year | Second Sem'), ('SYS', 'Second Year | Summer'), ('M', 'Major'), ('POS', 'Program of Study')], max_length=32),
        ),
    ]
